/*
 * Copyright (c) 2025-2026 Datalayer, Inc.
 * Distributed under the terms of the MIT License.
 */

import type {EditorThemeClasses} from 'lexical';

import './JupyterLexicalTheme.css';

const theme: EditorThemeClasses = {
  autocomplete: 'JupyterLexicalTheme__autocomplete',
  blockCursor: 'JupyterLexicalTheme__blockCursor',
  characterLimit: 'JupyterLexicalTheme__characterLimit',
  code: 'JupyterLexicalTheme__code',
  codeHighlight: {
    atrule: 'JupyterLexicalTheme__tokenAttr',
    attr: 'JupyterLexicalTheme__tokenAttr',
    boolean: 'JupyterLexicalTheme__tokenProperty',
    builtin: 'JupyterLexicalTheme__tokenSelector',
    cdata: 'JupyterLexicalTheme__tokenComment',
    char: 'JupyterLexicalTheme__tokenSelector',
    class: 'JupyterLexicalTheme__tokenFunction',
    'class-name': 'JupyterLexicalTheme__tokenFunction',
    comment: 'JupyterLexicalTheme__tokenComment',
    constant: 'JupyterLexicalTheme__tokenProperty',
    deleted: 'JupyterLexicalTheme__tokenDeleted',
    doctype: 'JupyterLexicalTheme__tokenComment',
    entity: 'JupyterLexicalTheme__tokenOperator',
    function: 'JupyterLexicalTheme__tokenFunction',
    important: 'JupyterLexicalTheme__tokenVariable',
    inserted: 'JupyterLexicalTheme__tokenInserted',
    keyword: 'JupyterLexicalTheme__tokenAttr',
    namespace: 'JupyterLexicalTheme__tokenVariable',
    number: 'JupyterLexicalTheme__tokenProperty',
    operator: 'JupyterLexicalTheme__tokenOperator',
    prolog: 'JupyterLexicalTheme__tokenComment',
    property: 'JupyterLexicalTheme__tokenProperty',
    punctuation: 'JupyterLexicalTheme__tokenPunctuation',
    regex: 'JupyterLexicalTheme__tokenVariable',
    selector: 'JupyterLexicalTheme__tokenSelector',
    string: 'JupyterLexicalTheme__tokenSelector',
    symbol: 'JupyterLexicalTheme__tokenProperty',
    tag: 'JupyterLexicalTheme__tokenProperty',
    unchanged: 'JupyterLexicalTheme__tokenUnchanged',
    url: 'JupyterLexicalTheme__tokenOperator',
    variable: 'JupyterLexicalTheme__tokenVariable',
  },
  embedBlock: {
    base: 'JupyterLexicalTheme__embedBlock',
    focus: 'JupyterLexicalTheme__embedBlockFocus',
  },
  hashtag: 'JupyterLexicalTheme__hashtag',
  heading: {
    h1: 'JupyterLexicalTheme__h1',
    h2: 'JupyterLexicalTheme__h2',
    h3: 'JupyterLexicalTheme__h3',
    h4: 'JupyterLexicalTheme__h4',
    h5: 'JupyterLexicalTheme__h5',
    h6: 'JupyterLexicalTheme__h6',
  },
  hr: 'JupyterLexicalTheme__hr',
  hrSelected: 'JupyterLexicalTheme__hrSelected',
  image: 'editor-image',
  indent: 'JupyterLexicalTheme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'JupyterLexicalTheme__layoutContainer',
  layoutItem: 'JupyterLexicalTheme__layoutItem',
  link: 'JupyterLexicalTheme__link',
  list: {
    checklist: 'JupyterLexicalTheme__checklist',
    listitem: 'JupyterLexicalTheme__listItem',
    listitemChecked: 'JupyterLexicalTheme__listItemChecked',
    listitemUnchecked: 'JupyterLexicalTheme__listItemUnchecked',
    nested: {
      listitem: 'JupyterLexicalTheme__nestedListItem',
    },
    olDepth: [
      'JupyterLexicalTheme__ol1',
      'JupyterLexicalTheme__ol2',
      'JupyterLexicalTheme__ol3',
      'JupyterLexicalTheme__ol4',
      'JupyterLexicalTheme__ol5',
    ],
    ul: 'JupyterLexicalTheme__ul',
  },
  ltr: 'JupyterLexicalTheme__ltr',
  mark: 'JupyterLexicalTheme__mark',
  markOverlap: 'JupyterLexicalTheme__markOverlap',
  paragraph: 'JupyterLexicalTheme__paragraph',
  quote: 'JupyterLexicalTheme__quote',
  rtl: 'JupyterLexicalTheme__rtl',
  specialText: 'JupyterLexicalTheme__specialText',
  tab: 'JupyterLexicalTheme__tabNode',
  table: 'JupyterLexicalTheme__table',
  tableAddColumns: 'JupyterLexicalTheme__tableAddColumns',
  tableAddRows: 'JupyterLexicalTheme__tableAddRows',
  tableAlignment: {
    center: 'JupyterLexicalTheme__tableAlignmentCenter',
    right: 'JupyterLexicalTheme__tableAlignmentRight',
  },
  tableCell: 'JupyterLexicalTheme__tableCell',
  tableCellActionButton: 'JupyterLexicalTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'JupyterLexicalTheme__tableCellActionButtonContainer',
  tableCellHeader: 'JupyterLexicalTheme__tableCellHeader',
  tableCellResizer: 'JupyterLexicalTheme__tableCellResizer',
  tableCellSelected: 'JupyterLexicalTheme__tableCellSelected',
  tableFrozenColumn: 'JupyterLexicalTheme__tableFrozenColumn',
  tableFrozenRow: 'JupyterLexicalTheme__tableFrozenRow',
  tableRowStriping: 'JupyterLexicalTheme__tableRowStriping',
  tableScrollableWrapper: 'JupyterLexicalTheme__tableScrollableWrapper',
  tableSelected: 'JupyterLexicalTheme__tableSelected',
  tableSelection: 'JupyterLexicalTheme__tableSelection',
  text: {
    bold: 'JupyterLexicalTheme__textBold',
    capitalize: 'JupyterLexicalTheme__textCapitalize',
    code: 'JupyterLexicalTheme__textCode',
    highlight: 'JupyterLexicalTheme__textHighlight',
    italic: 'JupyterLexicalTheme__textItalic',
    lowercase: 'JupyterLexicalTheme__textLowercase',
    strikethrough: 'JupyterLexicalTheme__textStrikethrough',
    subscript: 'JupyterLexicalTheme__textSubscript',
    superscript: 'JupyterLexicalTheme__textSuperscript',
    underline: 'JupyterLexicalTheme__textUnderline',
    underlineStrikethrough: 'JupyterLexicalTheme__textUnderlineStrikethrough',
    uppercase: 'JupyterLexicalTheme__textUppercase',
  },
};

export default theme;
