/*
 * Copyright (c) 2023-2025 Datalayer, Inc.
 * Distributed under the terms of the MIT License.
 */

import type { JSX, MutableRefObject } from 'react';
import type { LoroDoc } from 'loro-crdt';

import {
  type LoroCollaborationContextType,
  useLoroCollaborationContext,
} from './LoroCollaborationContext';
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import {
  type LoroBinding,
  createLoroBinding,
  type LoroProvider,
} from './collaboration';

// Type for the provider factory function
export type LoroProviderFactory = (id: string, loroDocMap: Map<string, LoroDoc>) => LoroProvider;
import type { EditorState, LexicalEditor } from 'lexical';
import { useEffect, useRef, useState } from 'react';

import {
  type LoroCursorsContainerRef,
  useLoroCollaboration,
  useLoroFocusTracking,
  useLoroHistory,
  type SyncLoroCursorPositionsFn,
} from './useLoroCollaboration';

// Initial editor state type (following YJS pattern)
export type InitialEditorStateType = 
  | null 
  | string 
  | EditorState 
  | ((editor: LexicalEditor) => void);


export interface ILoroCollaborationPluginPropsV2 {
  id: string;
  providerFactory: LoroProviderFactory;
  shouldBootstrap?: boolean;
  username?: string;
  cursorColor?: string;
  cursorsContainerRef?: MutableRefObject<HTMLElement | null>;
  initialEditorState?: InitialEditorStateType;
  // `awarenessData` parameter allows arbitrary data to be added to the awareness.
  awarenessData?: object;
  syncCursorPositionsFn?: SyncLoroCursorPositionsFn;
  // Callback props for peer management
  // Note: Two types of IDs in the system:
  // 1. WebSocket Client ID: Generated by server for each WebSocket connection (provider.clientId)
  // 2. Loro Peer ID: Generated by Loro CRDT system for each document peer (peer.id)
  onWebSocketClientIdChange?: (websocketClientId: string) => void;
  onLoroPeerIdChange?: (loroPeerId: string) => void;
  onAwarenessChange?: (awareness: Array<{peerId: string, userName: string, isCurrentUser?: boolean}>) => void;
};

/**
 * LoroCollaborationPlugin - Following YJS CollaborationPlugin pattern exactly
 * 
 * This plugin provides the main collaboration interface following the exact
 * same architecture as YJS CollaborationPlugin:
 * 
 * Key responsibilities:
 * 1. Context management - Get collaboration context (loroDocMap, name, color)
 * 2. Provider initialization - Create provider using factory with loroDocMap
 * 3. Binding creation - Create binding between editor and Loro document
 * 4. Lifecycle management - Set isCollabActive flag, clientID assignment
 * 5. Component orchestration - Pass everything to LoroCollaborationCursors
 */
export function LoroCollaborationPluginV2({
  id,
  providerFactory,
  shouldBootstrap,
  username,
  cursorColor,
  cursorsContainerRef,
  initialEditorState,
  awarenessData,
  syncCursorPositionsFn,
  onWebSocketClientIdChange,
  onLoroPeerIdChange,
  onAwarenessChange,
}: ILoroCollaborationPluginPropsV2): JSX.Element {
  const isBindingInitialized = useRef(false);
  const isProviderInitialized = useRef(false);

  // Get collaboration context (following YJS pattern exactly)
  const collabContext = useLoroCollaborationContext(username, cursorColor);

  // Extract values from context (following YJS pattern)
  const { loroDocMap, name, color } = collabContext;

  const [editor] = useLexicalComposerContext();

  // Set collaboration active state (following YJS pattern exactly)
  useEffect(() => {
    collabContext.isCollabActive = true;

    return () => {
      // Resetting flag only when unmount top level editor collab plugin. Nested
      // editors (e.g. image caption) should unmount without affecting it
      if (editor._parentEditor == null) {
        collabContext.isCollabActive = false;
      }
    };
  }, [collabContext, editor]);

  const [provider, setProvider] = useState<LoroProvider>();
  const [doc, setDoc] = useState<LoroDoc>();

  // Provider initialization (following YJS pattern exactly)
  useEffect(() => {
    if (isProviderInitialized.current) {
      return;
    }

    isProviderInitialized.current = true;

    // Create provider using factory with loroDocMap (following YJS pattern)
    const newProvider = providerFactory(id, loroDocMap);
    setProvider(newProvider);
    setDoc(loroDocMap.get(id));

    return () => {
      newProvider.disconnect();
    };
  }, [id, providerFactory, loroDocMap]);

  const [binding, setBinding] = useState<LoroBinding>();

  // Binding initialization (following YJS pattern exactly)
  useEffect(() => {
    if (!provider) {
      return;
    }

    if (isBindingInitialized.current) {
      return;
    }

    isBindingInitialized.current = true;

    // Create binding (following YJS pattern)
    const newBinding = createLoroBinding(
      editor,
      provider,
      id,
      doc || loroDocMap.get(id)!,
      loroDocMap,
    );
    setBinding(newBinding);

    // Register Loro peer ID with server after WebSocket connection is established
    const handleConnection = () => {
      if (newBinding && newBinding.clientID && provider.registerLoroPeerId) {
        console.log(`🆔 [PLUGIN] Registering Loro peer ID with server: ${newBinding.clientID}`);
        provider.registerLoroPeerId(newBinding.clientID);
      }
    };

    // Register on connection (if already connected) or wait for connection event
    if (provider.connected) {
      handleConnection();
    } else {
      provider.on('connect', handleConnection);
    }

    // Notify parent about Loro peer ID once binding is created
    if (onLoroPeerIdChange && newBinding.clientID) {
      onLoroPeerIdChange(newBinding.clientID);
    }

    return () => {
      // Clean up event listeners
      if (provider && provider.off) {
        provider.off('connect', handleConnection);
      }
      
      // TODO: Implement binding.root.destroy when Loro API is available
      // newBinding.root.destroy(newBinding);
      console.log('🧹 Cleaning up Loro binding');
    };
  }, [editor, provider, id, loroDocMap, doc, onLoroPeerIdChange]);

  // Wait for provider and binding (following YJS pattern exactly)
  if (!provider || !binding) {
    return <></>;
  }

  // Render cursors component (following YJS pattern exactly)
  return (
    <LoroCollaborationCursors
      awarenessData={awarenessData}
      binding={binding}
      collabContext={collabContext}
      color={color}
      cursorsContainerRef={cursorsContainerRef}
      editor={editor}
      id={id}
      initialEditorState={initialEditorState}
      name={name}
      provider={provider}
      setDoc={setDoc}
      shouldBootstrap={shouldBootstrap ?? false}
      loroDocMap={loroDocMap}
      syncCursorPositionsFn={syncCursorPositionsFn}
      onWebSocketClientIdChange={onWebSocketClientIdChange}
      onLoroPeerIdChange={onLoroPeerIdChange}
      onAwarenessChange={onAwarenessChange}
    />
  );
}

/**
 * LoroCollaborationCursors - Following YJS YjsCollaborationCursors pattern exactly
 * 
 * This component handles the actual collaboration hooks and cursor management:
 * 1. Main collaboration hook (useLoroCollaboration)
 * 2. History hook (useLoroHistory) 
 * 3. Focus tracking hook (useLoroFocusTracking)
 * 4. Client ID assignment to context
 * 5. Returns cursor portal
 */
function LoroCollaborationCursors({
  editor,
  id,
  provider,
  loroDocMap,
  name,
  color,
  shouldBootstrap,
  cursorsContainerRef,
  initialEditorState,
  awarenessData,
  collabContext,
  binding,
  setDoc,
  syncCursorPositionsFn,
  onWebSocketClientIdChange,
  onLoroPeerIdChange,
  onAwarenessChange,
}: {
  editor: LexicalEditor;
  id: string;
  provider: LoroProvider;
  loroDocMap: Map<string, LoroDoc>;
  name: string;
  color: string;
  shouldBootstrap: boolean;
  binding: LoroBinding;
  setDoc: React.Dispatch<React.SetStateAction<LoroDoc | undefined>>;
  cursorsContainerRef?: LoroCursorsContainerRef | undefined;
  initialEditorState?: InitialEditorStateType | undefined;
  awarenessData?: object;
  collabContext: LoroCollaborationContextType;
  syncCursorPositionsFn?: SyncLoroCursorPositionsFn;
  // Note: Two types of IDs in the system:
  // 1. WebSocket Client ID: Generated by server for each WebSocket connection (provider.clientId)
  // 2. Loro Peer ID: Generated by Loro CRDT system for each document peer (peer.id from awareness)
  onWebSocketClientIdChange?: (websocketClientId: string) => void;
  onLoroPeerIdChange?: (loroPeerId: string) => void;
  onAwarenessChange?: (awareness: Array<{peerId: string, userName: string, isCurrentUser?: boolean}>) => void;
}) {
  // Main collaboration hook (following YJS pattern exactly)
  const cursors = useLoroCollaboration(
    editor,
    id,
    provider,
    loroDocMap,
    name,
    color,
    shouldBootstrap,
    binding,
    setDoc,
    cursorsContainerRef,
    initialEditorState,
    awarenessData,
    syncCursorPositionsFn,
  );

  // Handle peer data from provider events
  useEffect(() => {
    if (!provider) return;

    // Set WebSocket client ID when available
    if (provider.clientId && onWebSocketClientIdChange) {
      onWebSocketClientIdChange(provider.clientId);
    }

    // Suppress unused parameter warning - onLoroPeerIdChange is used in parent component
    void onLoroPeerIdChange;

    const handleWelcome = (data: any) => {
      console.log(`🎯 [Welcome] Provider clientId: ${provider.clientId}, Welcome data:`, data);
      
      if (data.peers && Array.isArray(data.peers)) {
        const validPeers = data.peers.filter((peer: any) => peer.id && peer.websocketClientId);
        console.log(`🎯 [Welcome] Valid peers:`, validPeers);

        const awarenessData = validPeers.map((peer: any) => ({
          peerId: peer.id, // This is the Loro peer ID (CRDT concept)
          userName: peer.displayId || peer.id?.slice(-4) || 'User',
          isCurrentUser: peer.id === binding.clientID // Compare Loro peer ID with binding's clientID
        }));
        
        console.log(`🎯 [Welcome] Awareness data:`, awarenessData);
        onAwarenessChange?.(awarenessData);
      }
    };

    const handlePeerUpdate = (data: any) => {
      console.log(`🎯 [PeerUpdate] Provider clientId: ${provider.clientId}, Update data:`, data);
      
      if (data.peers && Array.isArray(data.peers) && onAwarenessChange) {
        const validPeers = data.peers.filter((peer: any) => peer.id && peer.websocketClientId);
        console.log(`🎯 [PeerUpdate] Valid peers:`, validPeers);

        // Group peers by their displayId to remove duplicates from same browser
        const peerMap = new Map();
        validPeers.forEach((peer: any) => {
          const displayId = peer.displayId || peer.id?.slice(-4) || 'User';
          const isCurrentUser = peer.id === binding.clientID; // Compare Loro peer ID with binding's clientID
          
          console.log(`🎯 [PeerUpdate] Processing peer: ${peer.websocketClientId}, isCurrentUser: ${isCurrentUser}, displayId: ${displayId}`);
          
          // If this is the current user's entry, always use it
          // Otherwise, only keep if we don't have an entry for this displayId or this one is newer
          if (isCurrentUser || !peerMap.has(displayId)) {
            peerMap.set(displayId, {
              peerId: peer.id, // Loro peer ID (CRDT concept)
              userName: displayId,
              isCurrentUser,
              websocketClientId: peer.websocketClientId // Keep WebSocket client ID for debugging
            });
          }
        });
        
        const awarenessData = Array.from(peerMap.values()).map(peer => ({
          peerId: peer.peerId,
          userName: peer.userName,
          isCurrentUser: peer.isCurrentUser
        }));
        
        console.log(`🎯 [PeerUpdate] Final awareness data:`, awarenessData);
        onAwarenessChange(awarenessData);
      }
    };

    provider.on('welcome', handleWelcome);
    provider.on('peerUpdate', handlePeerUpdate);

    return () => {
      provider.off('welcome', handleWelcome);
      provider.off('peerUpdate', handlePeerUpdate);
    };
  }, [provider, onWebSocketClientIdChange, onLoroPeerIdChange, onAwarenessChange, binding.clientID]);

  // Set client ID in context (following YJS pattern exactly)
  collabContext.clientID = binding.clientID;

  // Register hooks (following YJS pattern exactly)
  useLoroHistory(editor, binding);
  useLoroFocusTracking(editor, provider, name, color, awarenessData);

  return cursors;
}
